# conda env create -f environment.yaml
name: mindlessgen
channels:
  - conda-forge
dependencies:
  - ruff
  - coverage
  - numpy
  - pre-commit
  - pytest
  - tox
  - tqdm
  - pip:
      - covdefaults
