# Default configuration for the 'Mindless Molecule GENerator' (MindlessGen) package
# Following file locations are searched for in the following order:
# 1. Location specified by the `--config < str | Path >` command-line argument
# 2. Current working directory (`Path.cwd()`)
# 3. User's home directory (`Path.home()`)

[general]
# > Verbosity level defining the printout: Options: 0 = silent, 1 = default, 2 = verbose, 3 = debug
verbosity = 1
# > Number of parallel processes to use. Options: <int>
parallel = 1
# > Maximum number of generation/optimization try-and-error cycles per molecule. Options: <int>
max_cycles = 100
# > Number of molecules to generate. Options: <int>
num_molecules = 1
# > Do post-processing (checking for HL gap, etc.) after the optimization. Options: <bool>
postprocess = false

[generate]
# > Minimum number of atoms in the generated molecule. Options: <int>
min_num_atoms = 2
# > Maximum number of atoms in the generated molecule. Options: <int>
max_num_atoms = 100
# > Initial coordinate scaling factor. Options: <float>
init_scaling = 3.0
# > Increase in the coordinate scaling factor per trial after dist_threshold was not met. Options: <float>
increase_scaling_factor = 1.3
# > Distance threshold for the inital, randomly generated coordinates. Options: <float>
dist_threshold = 1.2
# > Atom types and their minimum and maximum occurrences. Format: "<element>:<min_count>-<max_count>"
# > Elements that are not specified are only added by random selection.
# > A star sign (*) can be used as a wildcard for integer value.
element_composition = "C:2-10, H:10-20, O:1-5, N:1-*"
# > Atom types that are not chosen for random selection. Format: "<element1>, <element2>, ..."
# > CAUTION: This option is overridden by the 'element_composition' option.
# > I.e., if an element is specified in 'element_composition' with an occurrence > 0, it will be added to the molecule anyway.
# > Example: forbidden_elements = "18,57-*"
forbidden_elements = "57-71"

[refine]
# > Maximum number of fragment optimization cycles. Options: <int>
max_frag_cycles = 100
# > Quantum Mechanics (QM) engine to use. Options: 'xtb', 'orca'
engine = "xtb"

[postprocess]
# > Engine for the post-processing part. Options: 'xtb', 'orca'
engine = "orca"
# > Optimize geometry in the post-processing part. Options: <bool>
optimize = true
# > Optimization cycles for the post-processing part. If not given, the program default is chosen. Options: <int>
opt_cycles = 5

[xtb]
# > Path to the xtb executable. Options: <str | Path>
xtb_path = "/path/to/xtb"

[orca]
# > Path to the orca executable. Options: <str | Path>
orca_path = "/path/to/orca"
# > Functional/Method: Options: <str>
functional = "PBE"
# > Basis set: Options: <str>
basis = "def2-SVP"
# > Gridsize for the numerical integration: Options: <int => 1> = coarse, <int = 2> => medium, <int = 3> => fine
gridsize = 1
# > Maximum number of SCF cycles: Options: <int>
scf_cycles = 100
